services:
  quote-api:
    image: mnepul/quote_api:v1
    networks:
      - quote-ntw

  quote-webapp:
    image: mnepul/quote_webapp:v1
    ports:
      - 5000:5000
    environment:
      - API_BASE_URL=http://quote-api:8000
      - WEBAPP_PORT=5000
    networks:
      - quote-ntw
    depends_on:
      - quote-api
  
networks:
  quote-ntw:
      driver: bridge